. evidence/lib.sh
PFA='https://localhost:9999/pf-admin-api/v1'; AUTH="-u Administrator:\$PING_ADMIN_PASSWORD -H 'X-XSRF-Header: PingFederate'"
G=~/Documents/GitHub/fleet.mpc.ad-gitops
ev_init CFG "Configuration as tested" "Sanitized copies of the configuration the results depend on, so the lab can be rebuilt or shown to someone else." "Everything the guides tell a customer to configure, in its working form." >/dev/null
ev_cmd CFG pf-x509-adapter "curl -sk $AUTH $PFA/idp/adapters/x509lab | jq '{id,name,pluginDescriptorRef:.pluginDescriptorRef.id,fields:[.configuration.fields[]|{(.name):.value}]|add,attribute_contract:[.attributeContract.coreAttributes[].name]}'" >/dev/null
ev_cmd CFG pf-trusted-cas "curl -sk $AUTH $PFA/certificates/ca | jq '[.items[]|{id,subjectDN,issuerDN,validFrom:.validFrom,expires:.expires,keySize}]'" >/dev/null
ev_cmd CFG pf-policy-contract "curl -sk $AUTH $PFA/authenticationPolicyContracts/fleetcontract | jq '{id,name,core:[.coreAttributes[].name],extended:[.extendedAttributes[].name]}'" >/dev/null
ev_cmd CFG pf-authentication-policy "curl -sk $AUTH $PFA/authenticationPolicies/default | jq '.authnSelectionTrees[0]|{name,adapter:.rootNode.action.authenticationSource.sourceRef.id,on_success:.rootNode.children[1].action.authenticationPolicyContractRef.id,lookup_1:.rootNode.children[1].action.attributeMapping.attributeSources[0].filterFields[0].value,lookup_2:.rootNode.children[1].action.attributeMapping.attributeSources[1].filterFields[0].value,fulfillment:.rootNode.children[1].action.attributeMapping.attributeContractFulfillment,criteria:.rootNode.children[1].action.attributeMapping.issuanceCriteria.conditionalCriteria}'" >/dev/null
ev_cmd CFG pf-oauth-test-client "curl -sk $AUTH $PFA/oauth/clients/labclient | jq '{clientId,name,grantTypes,redirectUris,restrictScopes,defaultAccessTokenManagerRef:.defaultAccessTokenManagerRef.id}'" >/dev/null
ev_cmd CFG pf-server-and-ports "curl -sk $AUTH $PFA/serverSettings | jq '{base_url:.rolesAndProtocols|keys}' 2>/dev/null; docker exec pingfederate sh -c 'grep -E \"^pf\\.(secondary\\.https|https)\\.port\" /opt/out/instance/bin/run.properties'; docker port pingfederate" >/dev/null
ev_cmd CFG fleet-gitops-policies "cat $G/lib/all/policies/ca-test.policies.yml $G/lib/macos/policies/duo-desktop-installed.policies.yml $G/lib/macos/policies/firefox-installed.policies.yml" >/dev/null
ev_cmd CFG fleet-gitops-fleet "cat $G/fleets/ping-duo-lab.yml; echo; echo '--- certificate authority (default.yml):'; grep -n -B2 -A8 'custom_scep_proxy' $G/default.yml | sed -E 's/(challenge: ).*/\\1<from a GitHub secret>/'" >/dev/null
ev_cmd CFG fleet-macos-scep-profile "cat $G/lib/macos/configuration-profiles/lab-ca-scep-user.mobileconfig" >/dev/null
ev_cmd CFG fleet-windows-scep-profile "cat $G/lib/windows/configuration-profiles/lab-ca-scep-user.xml | sed -E 's#(CAThumbprint</LocURI>.*<Data>)[^<]*#\\1<fleet secret variable>#'" >/dev/null
ev_cmd CFG fleet-chrome-autoselect-profile "cat $G/lib/macos/configuration-profiles/lab-chrome-autoselect.mobileconfig" >/dev/null
ev_cmd CFG duo-integrations-summary "echo 'Three Generic Trusted Endpoints integrations in Duo (Generic with Duo Desktop): macOS (active, group fleet-lab), Linux (active, group fleet-lab), Windows (not activated).'; echo 'Duo Web SDK app + policy: Trusted Endpoints = block endpoints that are not trusted, applied to the app and group fleet-lab.'; echo 'Test user: lab-test (Touch ID enrolled on the Mac; bypass code used on Linux).'; echo; echo 'Sync workflow (GitOps repo):'; cat $G/.github/workflows/duo-sync.yml | sed -n 1,25p" >/dev/null
